apiVersion: v1
kind: Pod
metadata:
  name: traffic-generator
  labels:
    app: traffic-generator
spec:
  containers:
    - name: traffic-generator
      image: yurikrupnik/wrk-m1:latest
      imagePullPolicy: IfNotPresent
      args:
        - sleep
        - "10000000"
  restartPolicy: Always
