apiVersion: v1
kind: Service
metadata:
  name: buster-fat-service
  labels:
    run: buster-fat-service
spec:
  type: LoadBalancer
  ports:
    - port: 1234
      protocol: TCP
      targetPort: 80
  selector:
    app: buster-fat
